version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-zoo-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-zoo-net
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic-kib-log-net
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic-kib-log-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash1:
    container_name: logstash1
    image: docker.elastic.co/logstash/logstash:8.13.4
    volumes:
      - ./utils/logstash-config/user_postgres.conf:/usr/share/logstash/pipeline/user-logstash.conf
      - ./utils/index-template/user-template.json:/usr/share/user-template.json
      - ./utils/driver/postgresql-42.7.3.jar:/usr/share/logstash/postgresql-jdbc.jar
    environment:
      - "xpack.monitoring.enabled=false"
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - elastic-kib-log-net

  logstash2:
    container_name: logstash2
    image: docker.elastic.co/logstash/logstash:8.13.4
    volumes:
      - ./utils/logstash-config/customer_postgres.conf:/usr/share/logstash/pipeline/customer_postgres.conf
      - ./utils/index-template/customer-template.json:/usr/share/customer-template.json
      - ./utils/driver/postgresql-42.7.3.jar:/usr/share/logstash/postgresql-jdbc.jar
    environment:
      - "xpack.monitoring.enabled=false"
    ports:
      - "5144:5144"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    networks:
      - elastic-kib-log-net

networks:
  elastic-kib-log-net:
    driver: bridge
  kafka-zoo-net:
    driver: bridge